/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 10 02:36:17 GMT 2022
 */

package cn.byhieg.designpatterntutorial.proxy.staticproxy;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import cn.byhieg.designpatterntutorial.proxy.staticproxy.ProxySubject;
import cn.byhieg.designpatterntutorial.proxy.staticproxy.RealSubject;
import cn.byhieg.designpatterntutorial.proxy.staticproxy.Subject;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ProxySubject_ESTest extends ProxySubject_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RealSubject realSubject0 = new RealSubject();
      ProxySubject proxySubject0 = new ProxySubject(realSubject0);
      proxySubject0.visit();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ProxySubject proxySubject0 = new ProxySubject((Subject) null);
      // Undeclared exception!
      try { 
        proxySubject0.visit();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("cn.byhieg.designpatterntutorial.proxy.staticproxy.ProxySubject", e);
      }
  }
}
