/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 10 02:58:08 GMT 2022
 */

package cn.byhieg.designpatterntutorial.proxy.staticproxy;

import org.junit.Test;
import static org.junit.Assert.*;
import cn.byhieg.designpatterntutorial.proxy.staticproxy.RealSubject;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RealSubject_ESTest extends RealSubject_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RealSubject realSubject0 = new RealSubject();
      realSubject0.visit();
  }
}
