/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 10 02:28:45 GMT 2022
 */

package cn.byhieg.reflectiontutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import cn.byhieg.reflectiontutorial.AnnotationObject;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AnnotationObject_ESTest extends AnnotationObject_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AnnotationObject annotationObject0 = new AnnotationObject();
      annotationObject0.doOtherThing("cn.byhieg.reflectiontutorial.AnnotationObject");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AnnotationObject annotationObject0 = new AnnotationObject();
      annotationObject0.doSomeThing();
  }
}
