/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 10 02:47:16 GMT 2022
 */

package cn.byhieg.reflectiontutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import cn.byhieg.reflectiontutorial.ExampleObject;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ExampleObject_ESTest extends ExampleObject_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ExampleObject exampleObject0 = new ExampleObject("");
      assertEquals(60, (int)exampleObject0.getScore());
      
      exampleObject0.setScore((Integer) null);
      exampleObject0.getScore();
      assertEquals(30, exampleObject0.age);
      assertEquals("byhieg", exampleObject0.getName());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ExampleObject exampleObject0 = new ExampleObject("x0_w");
      assertEquals(60, (int)exampleObject0.getScore());
      
      Integer integer0 = new Integer(0);
      exampleObject0.setScore(integer0);
      exampleObject0.getScore();
      assertEquals(30, exampleObject0.getAge());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ExampleObject exampleObject0 = new ExampleObject();
      assertEquals(60, (int)exampleObject0.getScore());
      
      Integer integer0 = new Integer((-799));
      exampleObject0.setScore(integer0);
      exampleObject0.getScore();
      assertEquals("byhieg", exampleObject0.getName());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ExampleObject exampleObject0 = new ExampleObject();
      assertEquals("byhieg", exampleObject0.getName());
      
      exampleObject0.setName((String) null);
      String string0 = exampleObject0.getName();
      assertEquals(30, exampleObject0.age);
      assertNull(string0);
      assertEquals(60, (int)exampleObject0.getScore());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ExampleObject exampleObject0 = new ExampleObject();
      assertEquals("byhieg", exampleObject0.getName());
      
      exampleObject0.name = "";
      exampleObject0.getName();
      assertEquals(60, (int)exampleObject0.getScore());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ExampleObject exampleObject0 = new ExampleObject(" OHYuhp2^=Jn\"tm8\"");
      assertEquals(30, exampleObject0.age);
      
      exampleObject0.age = 0;
      int int0 = exampleObject0.getAge();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ExampleObject exampleObject0 = new ExampleObject();
      exampleObject0.setAge((-718));
      int int0 = exampleObject0.getAge();
      assertEquals((-718), exampleObject0.age);
      assertEquals((-718), int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ExampleObject exampleObject0 = new ExampleObject();
      exampleObject0.run();
      assertEquals(30, exampleObject0.age);
      assertEquals(60, (int)exampleObject0.getScore());
      assertEquals("byhieg", exampleObject0.getName());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ExampleObject exampleObject0 = new ExampleObject();
      exampleObject0.doSomething();
      assertEquals("byhieg", exampleObject0.getName());
      assertEquals(30, exampleObject0.age);
      assertEquals(60, (int)exampleObject0.getScore());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ExampleObject exampleObject0 = new ExampleObject();
      int int0 = exampleObject0.getAge();
      assertEquals(60, (int)exampleObject0.getScore());
      assertEquals(30, int0);
      assertEquals("byhieg", exampleObject0.getName());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ExampleObject exampleObject0 = new ExampleObject();
      String string0 = exampleObject0.getName();
      assertEquals(30, exampleObject0.age);
      assertEquals("byhieg", string0);
      assertEquals(60, (int)exampleObject0.getScore());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ExampleObject exampleObject0 = new ExampleObject();
      exampleObject0.printName();
      assertEquals(30, exampleObject0.age);
      assertEquals("byhieg", exampleObject0.getName());
      assertEquals(60, (int)exampleObject0.getScore());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ExampleObject exampleObject0 = new ExampleObject();
      Integer integer0 = exampleObject0.getScore();
      assertEquals(60, (int)integer0);
      assertEquals("byhieg", exampleObject0.getName());
      assertEquals(30, exampleObject0.age);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Integer integer0 = new Integer(0);
      ExampleObject exampleObject0 = new ExampleObject(0, integer0);
      assertEquals(30, exampleObject0.age);
      assertEquals(60, (int)exampleObject0.getScore());
      assertEquals("byhieg", exampleObject0.getName());
  }
}
