/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 10 01:40:03 GMT 2022
 */

package cn.byhieg.designpatterntutorial.singleton;

import org.junit.Test;
import static org.junit.Assert.*;
import cn.byhieg.designpatterntutorial.singleton.DCLSingleton;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DCLSingleton_ESTest extends DCLSingleton_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DCLSingleton dCLSingleton0 = DCLSingleton.getSingleton();
      DCLSingleton dCLSingleton1 = DCLSingleton.getSingleton();
      assertSame(dCLSingleton1, dCLSingleton0);
  }
}
