/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 10 02:16:03 GMT 2022
 */

package cn.byhieg.designpatterntutorial.singleton;

import org.junit.Test;
import static org.junit.Assert.*;
import cn.byhieg.designpatterntutorial.singleton.EnumSingleton;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class EnumSingleton_ESTest extends EnumSingleton_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      EnumSingleton[] enumSingletonArray0 = EnumSingleton.values();
      assertEquals(1, enumSingletonArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      EnumSingleton enumSingleton0 = EnumSingleton.valueOf("SINGLETON");
      assertEquals(EnumSingleton.SINGLETON, enumSingleton0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      EnumSingleton enumSingleton0 = EnumSingleton.SINGLETON;
      enumSingleton0.doSometings();
  }
}
