#!/bin/bash
test_classes=(
com.thealgorithms.datastructures.lists.MergeSortedSinglyLinkedList
com.thealgorithms.datastructures.lists.Link
com.thealgorithms.datastructures.lists.CountSinglyLinkedListRecursion
com.thealgorithms.datastructures.lists.SinglyLinkedList
com.thealgorithms.datastructures.lists.CreateAndDetectLoop
com.thealgorithms.datastructures.lists.DoublyLinkedList
com.thealgorithms.datastructures.lists.LinkOperations
com.thealgorithms.datastructures.lists.SearchSinglyLinkedListRecursion
com.thealgorithms.datastructures.lists.Node
com.thealgorithms.datastructures.lists.CursorLinkedList
com.thealgorithms.datastructures.hashmap.hashing.GenericHashMapUsingArrayList
com.thealgorithms.datastructures.hashmap.hashing.HashMap
com.thealgorithms.datastructures.hashmap.hashing.HashMapCuckooHashing
com.thealgorithms.datastructures.hashmap.hashing.MainLinearProbing
com.thealgorithms.datastructures.hashmap.hashing.GenericHashMapUsingArray
com.thealgorithms.datastructures.hashmap.hashing.Intersection
com.thealgorithms.datastructures.hashmap.hashing.Main
com.thealgorithms.datastructures.hashmap.hashing.MainCuckooHashing
com.thealgorithms.datastructures.hashmap.hashing.HashMapLinearProbing
com.thealgorithms.datastructures.dynamicarray.DynamicArray
com.thealgorithms.datastructures.disjointsets.DisjointSets
com.thealgorithms.datastructures.disjointsets.Node
com.thealgorithms.datastructures.queues.CircularQueue
com.thealgorithms.datastructures.queues.GenericArrayListQueue
com.thealgorithms.datastructures.queues.PriorityQueues
com.thealgorithms.datastructures.queues.Queues
com.thealgorithms.datastructures.queues.Deques
com.thealgorithms.datastructures.queues.Queue
com.thealgorithms.datastructures.queues.PriorityQueue
com.thealgorithms.datastructures.queues.LinkedQueue
com.thealgorithms.datastructures.graphs.AdjacencyList
com.thealgorithms.datastructures.graphs.ConnectedComponent
com.thealgorithms.datastructures.graphs.AdjacencyListGraph
com.thealgorithms.datastructures.graphs.Kruskal
com.thealgorithms.datastructures.graphs.Cycles
com.thealgorithms.datastructures.graphs.AdjacencyMatrixGraph
com.thealgorithms.datastructures.graphs.BipartiteGrapfDFS
com.thealgorithms.datastructures.graphs.BellmanFord
com.thealgorithms.datastructures.graphs.Cycle
com.thealgorithms.datastructures.graphs.FloydWarshall
com.thealgorithms.datastructures.graphs.Graph
com.thealgorithms.datastructures.graphs.A_Star
com.thealgorithms.datastructures.graphs.PrimMST
com.thealgorithms.datastructures.graphs.MatrixGraphs
com.thealgorithms.datastructures.graphs.dijkstras
com.thealgorithms.datastructures.graphs.Graphs
com.thealgorithms.datastructures.graphs.HamiltonianCycle
com.thealgorithms.datastructures.graphs.TopologicalSort
com.thealgorithms.datastructures.graphs.KahnsAlgorithm
com.thealgorithms.datastructures.bloomfilter.BloomFilter
com.thealgorithms.datastructures.bags.Bag
com.thealgorithms.datastructures.heaps.EmptyHeapException
com.thealgorithms.datastructures.heaps.GenericHeap
com.thealgorithms.datastructures.heaps.HeapElement
com.thealgorithms.datastructures.heaps.FibonacciHeap
com.thealgorithms.datastructures.heaps.MaxHeap
com.thealgorithms.datastructures.heaps.MinPriorityQueue
com.thealgorithms.datastructures.heaps.MinHeap
com.thealgorithms.datastructures.heaps.Heap
com.thealgorithms.datastructures.caches.LRUCache
com.thealgorithms.datastructures.caches.MRUCache
com.thealgorithms.datastructures.caches.LFUCache
com.thealgorithms.backtracking.NQueens
com.thealgorithms.backtracking.Permutation
com.thealgorithms.backtracking.PowerSum
com.thealgorithms.backtracking.MazeRecursion
com.thealgorithms.backtracking.Combination
com.thealgorithms.backtracking.FloodFill
com.thealgorithms.backtracking.KnightsTour
com.thealgorithms.others.KochSnowflake
com.thealgorithms.others.BrianKernighanAlgorithm
com.thealgorithms.others.SkylineProblem
com.thealgorithms.others.CRCAlgorithm
com.thealgorithms.others.NextFit
com.thealgorithms.others.BoyerMoore
com.thealgorithms.others.Process
com.thealgorithms.others.RabinKarp
com.thealgorithms.others.ReturnSubsequence
com.thealgorithms.others.Dijkstra
com.thealgorithms.others.EulersFunction
com.thealgorithms.others.MiniMaxAlgorithm
com.thealgorithms.others.FirstFitCPU
com.thealgorithms.others.ThreeSum
com.thealgorithms.others.cn.HammingDistance
com.thealgorithms.others.ArrayLeftRotation
com.thealgorithms.others.Damm
com.thealgorithms.others.LinearCongruentialGenerator
com.thealgorithms.others.Krishnamurthy
com.thealgorithms.others.Verhoeff
com.thealgorithms.others.CountWords
com.thealgorithms.others.Trieac
com.thealgorithms.others.Luhn
com.thealgorithms.others.ReverseStackUsingRecursion
com.thealgorithms.others.TowerOfHanoi
com.thealgorithms.others.KMP
com.thealgorithms.others.FloydTriangle
com.thealgorithms.others.Schedule
com.thealgorithms.others.WorstFitCPU
com.thealgorithms.others.BestFitCPU
com.thealgorithms.others.Huffman
com.thealgorithms.others.RootPrecision
com.thealgorithms.others.Graph
com.thealgorithms.others.QueueWithStack
com.thealgorithms.others.countSetBits
com.thealgorithms.others.StackPostfixNotation
com.thealgorithms.others.MyComparator
com.thealgorithms.others.CountChar
com.thealgorithms.others.PageRank
com.thealgorithms.others.Rotate_by_90_degree
com.thealgorithms.others.HappyNumbersSeq
com.thealgorithms.others.Sudoku
com.thealgorithms.others.SieveOfEratosthenes
com.thealgorithms.others.Rotate
com.thealgorithms.others.StringMatchFiniteAutomata
com.thealgorithms.others.SJF
com.thealgorithms.others.RemoveDuplicateFromString
com.thealgorithms.others.GuassLegendre
com.thealgorithms.others.QueueUsingTwoStacks
com.thealgorithms.others.TopKWords
com.thealgorithms.others.BFPRT
com.thealgorithms.others.PerlinNoise
com.thealgorithms.others.CRC32
com.thealgorithms.others.BankersAlgorithm
com.thealgorithms.others.InsertDeleteInArray
com.thealgorithms.others.LowestBasePalindrome
com.thealgorithms.others.FibbonaciSeries
com.thealgorithms.others.TwoPointers
com.thealgorithms.others.Mandelbrot
com.thealgorithms.others.MemoryManagementAlgorithms
com.thealgorithms.others.HuffmanNode
com.thealgorithms.others.PasswordGen
com.thealgorithms.minimizinglateness.MinimizingLateness
com.thealgorithms.ciphers.Polybius
com.thealgorithms.ciphers.AES
com.thealgorithms.ciphers.RSA
com.thealgorithms.ciphers.SimpleSubstitutionCipher
com.thealgorithms.ciphers.Caesar
com.thealgorithms.ciphers.a5.LFSR
com.thealgorithms.ciphers.a5.A5Cipher
com.thealgorithms.ciphers.a5.CompositeLFSR
com.thealgorithms.ciphers.a5.Utils
com.thealgorithms.ciphers.a5.A5KeyStreamGenerator
com.thealgorithms.ciphers.a5.BaseLFSR
com.thealgorithms.ciphers.SimpleSubCipher
com.thealgorithms.ciphers.ColumnarTranspositionCipher
com.thealgorithms.ciphers.AffineCipher
com.thealgorithms.ciphers.Blowfish
com.thealgorithms.ciphers.HillCipher
com.thealgorithms.ciphers.Vigenere
com.thealgorithms.ciphers.ProductCipher
com.thealgorithms.ciphers.AESEncryption
com.thealgorithms.divideandconquer.StrassenMatrixMultiplication
com.thealgorithms.divideandconquer.ClosestPair
com.thealgorithms.divideandconquer.BinaryExponentiation
com.thealgorithms.divideandconquer.SkylineAlgorithm
com.thealgorithms.maths.MaxValue
com.thealgorithms.maths.PollardRho
com.thealgorithms.maths.LinearDiophantineEquationsSolver
com.thealgorithms.maths.PowRecursion
com.thealgorithms.maths.Factorial
com.thealgorithms.maths.GCD
com.thealgorithms.maths.FindMin
com.thealgorithms.maths.ADTFraction
com.thealgorithms.maths.PiNilakantha
com.thealgorithms.maths.NumberOfDigits
com.thealgorithms.maths.FactorialRecursion
com.thealgorithms.maths.VampireNumber
com.thealgorithms.maths.KrishnamurthyNumber
com.thealgorithms.maths.LeastCommonMultiple
com.thealgorithms.maths.PrimeCheck
com.thealgorithms.maths.ConvolutionFFT
com.thealgorithms.maths.FindMinRecursion
com.thealgorithms.maths.AliquotSum
com.thealgorithms.maths.AbsoluteMax
com.thealgorithms.maths.JugglerSequence
com.thealgorithms.maths.SumWithoutArithmeticOperators
com.thealgorithms.maths.SquareRootWithBabylonianMethod
com.thealgorithms.maths.DeterminantOfMatrix
com.thealgorithms.maths.FFT
com.thealgorithms.maths.PrimeFactorization
com.thealgorithms.maths.PalindromeNumber
com.thealgorithms.maths.Mode
com.thealgorithms.maths.KaprekarNumbers
com.thealgorithms.maths.SimpsonIntegration
com.thealgorithms.maths.AbsoluteValue
com.thealgorithms.maths.PythagoreanTriple
com.thealgorithms.maths.CircularConvolutionFFT
com.thealgorithms.maths.LeonardoNumber
com.thealgorithms.maths.BinomialCoefficient
com.thealgorithms.maths.PowerOfTwoOrNot
com.thealgorithms.maths.FindKthNumber
com.thealgorithms.maths.SumOfArithmeticSeries
com.thealgorithms.maths.StandardDeviation
com.thealgorithms.maths.AbsoluteMin
com.thealgorithms.maths.Convolution
com.thealgorithms.maths.MobiusFunction
com.thealgorithms.maths.MinValue
com.thealgorithms.maths.LiouvilleLambdaFunction
com.thealgorithms.maths.GCDRecursion
com.thealgorithms.maths.DudeneyNumber
com.thealgorithms.maths.GenericRoot
com.thealgorithms.maths.FastInverseSqrt
com.thealgorithms.maths.FindMaxRecursion
com.thealgorithms.maths.DigitalRoot
com.thealgorithms.maths.AutomorphicNumber
com.thealgorithms.maths.HarshadNumber
com.thealgorithms.maths.PerfectCube
com.thealgorithms.maths.TwinPrime
com.thealgorithms.maths.VectorCrossProduct
com.thealgorithms.maths.PascalTriangle
com.thealgorithms.maths.SquareRootWithNewtonRaphsonMethod
com.thealgorithms.maths.Median
com.thealgorithms.maths.Area
com.thealgorithms.maths.NonRepeatingElement
com.thealgorithms.maths.TrinomialTriangle
com.thealgorithms.maths.DistanceFormula
com.thealgorithms.maths.FFTBluestein
com.thealgorithms.maths.LucasSeries
com.thealgorithms.maths.PronicNumber
com.thealgorithms.maths.Combinations
com.thealgorithms.maths.NthUglyNumber
com.thealgorithms.maths.Armstrong
com.thealgorithms.maths.Average
com.thealgorithms.maths.Pow
com.thealgorithms.maths.ParseInteger
com.thealgorithms.maths.Gaussian
com.thealgorithms.maths.KeithNumber
com.thealgorithms.maths.HeronsFormula
com.thealgorithms.maths.MatrixUtil
com.thealgorithms.maths.Perimeter
com.thealgorithms.maths.JosephusProblem
com.thealgorithms.maths.ReverseNumber
com.thealgorithms.maths.FindMax
com.thealgorithms.maths.Volume
com.thealgorithms.maths.AmicableNumber
com.thealgorithms.maths.Ceil
com.thealgorithms.maths.RomanNumeralUtil
com.thealgorithms.maths.PerfectNumber
com.thealgorithms.maths.SumOfDigits
com.thealgorithms.maths.StandardScore
com.thealgorithms.maths.BinaryPow
com.thealgorithms.maths.FibonacciNumber
com.thealgorithms.maths.PerfectSquare
com.thealgorithms.maths.CollatzConjecture
com.thealgorithms.maths.Floor
com.thealgorithms.maths.MagicSquare
com.thealgorithms.maths.EulerMethod
com.thealgorithms.maths.FibonacciJavaStreams
com.thealgorithms.audiofilters.IIRFilter
com.thealgorithms.dynamicprogramming.Fibonacci
com.thealgorithms.dynamicprogramming.BruteForceKnapsack
com.thealgorithms.dynamicprogramming.RodCutting
com.thealgorithms.dynamicprogramming.PalindromicPartitioning
com.thealgorithms.dynamicprogramming.DP
com.thealgorithms.dynamicprogramming.LongestCommonSubsequence
com.thealgorithms.dynamicprogramming.MemoizationTechniqueKnapsack
com.thealgorithms.dynamicprogramming.LongestAlternatingSubsequence
com.thealgorithms.dynamicprogramming.MinimumSumPartition
com.thealgorithms.dynamicprogramming.LongestValidParentheses
com.thealgorithms.dynamicprogramming.RegexMatching
com.thealgorithms.dynamicprogramming.Knapsack
com.thealgorithms.dynamicprogramming.WineProblem
com.thealgorithms.dynamicprogramming.SubsetSum
com.thealgorithms.dynamicprogramming.MatrixChainMultiplication
com.thealgorithms.dynamicprogramming.EditDistance
com.thealgorithms.dynamicprogramming.FordFulkerson
com.thealgorithms.dynamicprogramming.MinimumPathSum
com.thealgorithms.dynamicprogramming.NewManShanksPrime
com.thealgorithms.dynamicprogramming.DyanamicProgrammingKnapsack
com.thealgorithms.dynamicprogramming.UniquePaths
com.thealgorithms.dynamicprogramming.LongestPalindromicSubsequence
com.thealgorithms.dynamicprogramming.CountFriendsPairing
com.thealgorithms.dynamicprogramming.CoinChange
com.thealgorithms.dynamicprogramming.BoardPath
com.thealgorithms.dynamicprogramming.Matrix
com.thealgorithms.dynamicprogramming.MatrixChainRecursiveTopDownMemoisation
com.thealgorithms.dynamicprogramming.BoundaryFill
com.thealgorithms.dynamicprogramming.Sum_Of_Subset
com.thealgorithms.dynamicprogramming.KadaneAlgorithm
com.thealgorithms.dynamicprogramming.CatalanNumber
com.thealgorithms.dynamicprogramming.ShortestSuperSequence
com.thealgorithms.dynamicprogramming.LongestIncreasingSubsequence
com.thealgorithms.dynamicprogramming.KnapsackMemoization
com.thealgorithms.dynamicprogramming.EggDropping
com.thealgorithms.dynamicprogramming.LongestPalindromicSubstring
com.thealgorithms.dynamicprogramming.LevenshteinDistance
com.thealgorithms.devutils.searches.MatrixSearchAlgorithm
com.thealgorithms.devutils.searches.SearchAlgorithm
com.thealgorithms.devutils.nodes.SimpleTreeNode
com.thealgorithms.devutils.nodes.LargeTreeNode
com.thealgorithms.devutils.nodes.SimpleNode
com.thealgorithms.devutils.nodes.TreeNode
com.thealgorithms.devutils.nodes.Node
com.thealgorithms.devutils.entities.ProcessDetails
com.thealgorithms.sorts.BucketSort
com.thealgorithms.sorts.InsertionSort
com.thealgorithms.sorts.SortUtils
com.thealgorithms.sorts.BubbleSort
com.thealgorithms.sorts.CocktailShakerSort
com.thealgorithms.sorts.HeapSort
com.thealgorithms.sorts.CountingSort
com.thealgorithms.sorts.OddEvenSort
com.thealgorithms.sorts.RadixSort
com.thealgorithms.sorts.CircleSort
com.thealgorithms.sorts.StoogeSort
com.thealgorithms.sorts.PigeonholeSort
com.thealgorithms.sorts.TimSort
com.thealgorithms.sorts.WiggleSort
com.thealgorithms.sorts.SortAlgorithm
com.thealgorithms.sorts.DNFSort
com.thealgorithms.sorts.BitonicSort
com.thealgorithms.sorts.SlowSort
com.thealgorithms.sorts.CycleSort
com.thealgorithms.sorts.GnomeSort
com.thealgorithms.sorts.SwapSort
com.thealgorithms.sorts.BogoSort
com.thealgorithms.sorts.PancakeSort
com.thealgorithms.sorts.DutchNationalFlagSort
com.thealgorithms.sorts.StrandSort
com.thealgorithms.sorts.Task2
com.thealgorithms.sorts.Task
com.thealgorithms.sorts.BubbleSortRecursion
com.thealgorithms.sorts.MergeSortRecursive
com.thealgorithms.sorts.App
com.thealgorithms.sorts.SelectionSort
com.thealgorithms.sorts.TreeSort
com.thealgorithms.sorts.SimpleSort
com.thealgorithms.sorts.CombSort
com.thealgorithms.sorts.ShellSort
com.thealgorithms.sorts.Task1
com.thealgorithms.sorts.QuickSort
com.thealgorithms.sorts.Node
com.thealgorithms.sorts.MergeSortNoExtraSpace
com.thealgorithms.sorts.LinkList_Sort
com.thealgorithms.sorts.TopologicalSort
com.thealgorithms.sorts.MergeSort
com.thealgorithms.sorts.BinaryInsertionSort
)

#total_time=18115
total_time=0

jpf_path={path-to-RunJPF.jar} #the end of path should be "build/RunJPF.jar"
classpath={path-to-classes}

for class in ${test_classes[@]}
do
  tmp=(${class//./ })
  echo "Begin generate tests for $class"
  START_TIME=$(date +%s)
  echo "Begin generate tests for $class, start time: $START_TIME" >> jpf_log.txt
  java -Xmx1024m -ea -jar $jpf_path +classpath=$classpath $class >> jpf.txt
  END_TIME=$(date +%s)
  echo "$class end time: $END_TIME"
  echo "$class end time: $END_TIME" >> jpf_log.txt
  EXECUTING_TIME=`expr $END_TIME - $START_TIME`
  echo "$class runtime: $EXECUTING_TIME (seconds)"
  echo "$class runtime: $EXECUTING_TIME (seconds)" >> jpf_log.txt
  total_time=$((${total_time} + $EXECUTING_TIME))
  echo "total time: $total_time"
  echo "total time: $total_time" >> jpf_log.txt
  echo "" >> jpf_log.txt
done
