/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 10 00:57:07 GMT 2022
 */

package cn.byhieg.algorithmtutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import cn.byhieg.algorithmtutorial.GraphMatrix;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GraphMatrix_ESTest extends GraphMatrix_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GraphMatrix.Weight[][] graphMatrix_WeightArray0 = new GraphMatrix.Weight[4][6];
      GraphMatrix graphMatrix0 = new GraphMatrix(graphMatrix_WeightArray0);
      graphMatrix0.dijkstra(3, 3);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      GraphMatrix.Weight[][] graphMatrix_WeightArray0 = new GraphMatrix.Weight[9][0];
      GraphMatrix.Weight[] graphMatrix_WeightArray1 = new GraphMatrix.Weight[7];
      GraphMatrix.Weight graphMatrix_Weight0 = new GraphMatrix.Weight();
      graphMatrix_WeightArray1[0] = graphMatrix_Weight0;
      graphMatrix_WeightArray1[1] = graphMatrix_Weight0;
      graphMatrix_WeightArray1[2] = graphMatrix_WeightArray1[0];
      graphMatrix_WeightArray1[3] = graphMatrix_WeightArray1[2];
      graphMatrix_WeightArray1[4] = graphMatrix_Weight0;
      GraphMatrix.Weight graphMatrix_Weight1 = new GraphMatrix.Weight(1073741830);
      graphMatrix_WeightArray1[5] = graphMatrix_Weight1;
      graphMatrix_WeightArray0[2] = graphMatrix_WeightArray1;
      graphMatrix_WeightArray0[3] = graphMatrix_WeightArray0[2];
      GraphMatrix graphMatrix0 = new GraphMatrix(graphMatrix_WeightArray0);
      Integer integer0 = new Integer(3);
      // Undeclared exception!
      try { 
        graphMatrix0.DFS(integer0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      GraphMatrix.Weight[][] graphMatrix_WeightArray0 = new GraphMatrix.Weight[7][8];
      GraphMatrix.Weight[] graphMatrix_WeightArray1 = new GraphMatrix.Weight[5];
      GraphMatrix.Weight graphMatrix_Weight0 = new GraphMatrix.Weight();
      graphMatrix_WeightArray1[1] = graphMatrix_Weight0;
      GraphMatrix.Weight graphMatrix_Weight1 = new GraphMatrix.Weight(0);
      graphMatrix_WeightArray1[2] = graphMatrix_Weight1;
      graphMatrix_WeightArray0[0] = graphMatrix_WeightArray1;
      GraphMatrix graphMatrix0 = new GraphMatrix(graphMatrix_WeightArray0);
      graphMatrix_Weight1.weight = 1073741849;
      Integer integer0 = new Integer(0);
      // Undeclared exception!
      try { 
        graphMatrix0.BFS(integer0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("cn.byhieg.algorithmtutorial.GraphMatrix", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      GraphMatrix.Weight graphMatrix_Weight0 = new GraphMatrix.Weight(0);
      GraphMatrix.Weight[][] graphMatrix_WeightArray0 = new GraphMatrix.Weight[2][0];
      GraphMatrix.Weight[] graphMatrix_WeightArray1 = new GraphMatrix.Weight[6];
      graphMatrix_WeightArray1[0] = graphMatrix_Weight0;
      graphMatrix_WeightArray1[1] = graphMatrix_Weight0;
      graphMatrix_WeightArray1[2] = graphMatrix_Weight0;
      graphMatrix_WeightArray0[0] = graphMatrix_WeightArray1;
      GraphMatrix graphMatrix0 = new GraphMatrix(graphMatrix_WeightArray0);
      Integer integer0 = new Integer(0);
      // Undeclared exception!
      try { 
        graphMatrix0.DFS(integer0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      GraphMatrix.Weight[][] graphMatrix_WeightArray0 = new GraphMatrix.Weight[4][9];
      GraphMatrix.Weight[] graphMatrix_WeightArray1 = new GraphMatrix.Weight[6];
      GraphMatrix.Weight graphMatrix_Weight0 = new GraphMatrix.Weight(1);
      graphMatrix_WeightArray1[0] = graphMatrix_Weight0;
      graphMatrix_WeightArray1[2] = graphMatrix_Weight0;
      graphMatrix_WeightArray1[3] = graphMatrix_Weight0;
      graphMatrix_WeightArray1[4] = graphMatrix_WeightArray1[0];
      graphMatrix_WeightArray0[1] = graphMatrix_WeightArray1;
      GraphMatrix graphMatrix0 = new GraphMatrix(graphMatrix_WeightArray0);
      Integer integer0 = new Integer(1);
      // Undeclared exception!
      try { 
        graphMatrix0.BFS(integer0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 4
         //
         verifyException("cn.byhieg.algorithmtutorial.GraphMatrix", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      GraphMatrix.Weight[][] graphMatrix_WeightArray0 = new GraphMatrix.Weight[3][6];
      GraphMatrix.Weight graphMatrix_Weight0 = new GraphMatrix.Weight();
      GraphMatrix.Weight[] graphMatrix_WeightArray1 = new GraphMatrix.Weight[3];
      graphMatrix_WeightArray1[1] = graphMatrix_Weight0;
      graphMatrix_WeightArray1[2] = graphMatrix_Weight0;
      graphMatrix_Weight0.weight = (-806);
      graphMatrix_WeightArray0[0] = graphMatrix_WeightArray1;
      graphMatrix_WeightArray0[1] = graphMatrix_WeightArray1;
      GraphMatrix graphMatrix0 = new GraphMatrix(graphMatrix_WeightArray0);
      // Undeclared exception!
      try { 
        graphMatrix0.dijkstra(0, (-1612));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         verifyException("cn.byhieg.algorithmtutorial.GraphMatrix", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      GraphMatrix.Weight[][] graphMatrix_WeightArray0 = new GraphMatrix.Weight[4][6];
      GraphMatrix.Weight graphMatrix_Weight0 = new GraphMatrix.Weight();
      GraphMatrix.Weight graphMatrix_Weight1 = new GraphMatrix.Weight();
      GraphMatrix.Weight[] graphMatrix_WeightArray1 = new GraphMatrix.Weight[13];
      graphMatrix_WeightArray1[1] = graphMatrix_Weight0;
      graphMatrix_WeightArray1[2] = graphMatrix_Weight0;
      graphMatrix_Weight1.weight = 3;
      graphMatrix_WeightArray1[3] = graphMatrix_Weight1;
      graphMatrix_WeightArray0[0] = graphMatrix_WeightArray1;
      graphMatrix_WeightArray0[3] = graphMatrix_WeightArray1;
      GraphMatrix graphMatrix0 = new GraphMatrix(graphMatrix_WeightArray0);
      graphMatrix0.dijkstra(0, 3);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      GraphMatrix.Weight[][] graphMatrix_WeightArray0 = new GraphMatrix.Weight[3][6];
      GraphMatrix graphMatrix0 = new GraphMatrix(graphMatrix_WeightArray0);
      // Undeclared exception!
      try { 
        graphMatrix0.dijkstra(0, (-1612));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("cn.byhieg.algorithmtutorial.GraphMatrix", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      GraphMatrix.Weight[][] graphMatrix_WeightArray0 = new GraphMatrix.Weight[15][0];
      GraphMatrix graphMatrix0 = new GraphMatrix(graphMatrix_WeightArray0);
      Integer integer0 = new Integer(5);
      graphMatrix0.DFS(integer0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      GraphMatrix.Weight[][] graphMatrix_WeightArray0 = new GraphMatrix.Weight[15][8];
      GraphMatrix.Weight[] graphMatrix_WeightArray1 = new GraphMatrix.Weight[4];
      GraphMatrix.Weight graphMatrix_Weight0 = new GraphMatrix.Weight();
      graphMatrix_WeightArray1[1] = graphMatrix_Weight0;
      GraphMatrix.Weight graphMatrix_Weight1 = new GraphMatrix.Weight(0);
      graphMatrix_WeightArray1[2] = graphMatrix_Weight0;
      graphMatrix_WeightArray1[3] = graphMatrix_Weight1;
      graphMatrix_WeightArray0[0] = graphMatrix_WeightArray1;
      graphMatrix_WeightArray0[3] = graphMatrix_WeightArray1;
      GraphMatrix graphMatrix0 = new GraphMatrix(graphMatrix_WeightArray0);
      Integer integer0 = new Integer(0);
      graphMatrix0.BFS(integer0);
  }
}
