/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 10 02:33:48 GMT 2022
 */

package cn.byhieg.collectiontutorial.listtutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import cn.byhieg.collectiontutorial.listtutorial.LinkedListDemo;
import java.util.LinkedList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LinkedListDemo_ESTest extends LinkedListDemo_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LinkedListDemo linkedListDemo0 = new LinkedListDemo();
      linkedListDemo0.setList((LinkedList) null);
      LinkedList<Object> linkedList0 = linkedListDemo0.getList();
      assertNull(linkedList0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LinkedListDemo linkedListDemo0 = new LinkedListDemo();
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      linkedList0.offer(linkedListDemo0);
      linkedListDemo0.setList(linkedList0);
      LinkedList<Object> linkedList1 = linkedListDemo0.getList();
      assertSame(linkedList1, linkedList0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LinkedListDemo linkedListDemo0 = new LinkedListDemo();
      LinkedList<Object> linkedList0 = linkedListDemo0.getList();
      assertEquals(0, linkedList0.size());
  }
}
