/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 10 02:13:39 GMT 2022
 */

package cn.byhieg.designpatterntutorial.builder;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import cn.byhieg.designpatterntutorial.builder.SimpleDialog;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SimpleDialog_ESTest extends SimpleDialog_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SimpleDialog simpleDialog0 = new SimpleDialog();
      simpleDialog0.controller = null;
      // Undeclared exception!
      try { 
        simpleDialog0.setNegativeButton("N Is4<HF}<d");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("cn.byhieg.designpatterntutorial.builder.SimpleDialog", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SimpleDialog.Builder simpleDialog_Builder0 = new SimpleDialog.Builder();
      SimpleDialog simpleDialog0 = simpleDialog_Builder0.create();
      simpleDialog0.controller = null;
      // Undeclared exception!
      try { 
        simpleDialog0.setIcon("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("cn.byhieg.designpatterntutorial.builder.SimpleDialog", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SimpleDialog simpleDialog0 = new SimpleDialog();
      simpleDialog0.controller = null;
      // Undeclared exception!
      try { 
        simpleDialog0.setMessage((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("cn.byhieg.designpatterntutorial.builder.SimpleDialog", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      SimpleDialog.Builder simpleDialog_Builder0 = new SimpleDialog.Builder();
      SimpleDialog simpleDialog0 = simpleDialog_Builder0.create();
      simpleDialog0.setNegativeButton("/ i");
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SimpleDialog.Builder simpleDialog_Builder0 = new SimpleDialog.Builder();
      SimpleDialog simpleDialog0 = simpleDialog_Builder0.create();
      simpleDialog0.setIcon("p85[<T0F");
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      SimpleDialog.Builder simpleDialog_Builder0 = new SimpleDialog.Builder();
      SimpleDialog simpleDialog0 = simpleDialog_Builder0.create();
      simpleDialog0.setPositiveButton("cn.byhieg.designpatterntutorial.builder.SimpleDialogController$DialogParams");
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SimpleDialog.Builder simpleDialog_Builder0 = new SimpleDialog.Builder();
      SimpleDialog simpleDialog0 = simpleDialog_Builder0.create();
      simpleDialog0.setMessage((String) null);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SimpleDialog.Builder simpleDialog_Builder0 = new SimpleDialog.Builder();
      SimpleDialog.Builder simpleDialog_Builder1 = simpleDialog_Builder0.setNegativeButton("TB|AKTP'Uq^SJ4LqA");
      assertSame(simpleDialog_Builder1, simpleDialog_Builder0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SimpleDialog.Builder simpleDialog_Builder0 = new SimpleDialog.Builder();
      SimpleDialog simpleDialog0 = simpleDialog_Builder0.create();
      simpleDialog0.setTitle(" negativeButton");
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SimpleDialog.Builder simpleDialog_Builder0 = new SimpleDialog.Builder();
      SimpleDialog.Builder simpleDialog_Builder1 = simpleDialog_Builder0.setIcon("");
      assertSame(simpleDialog_Builder1, simpleDialog_Builder0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      SimpleDialog.Builder simpleDialog_Builder0 = new SimpleDialog.Builder();
      SimpleDialog.Builder simpleDialog_Builder1 = simpleDialog_Builder0.setTitle("lGw?Wy0$3H: D__gt:4");
      assertSame(simpleDialog_Builder0, simpleDialog_Builder1);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      SimpleDialog.Builder simpleDialog_Builder0 = new SimpleDialog.Builder();
      SimpleDialog.Builder simpleDialog_Builder1 = simpleDialog_Builder0.setPositiveButton(":jhoEI");
      assertSame(simpleDialog_Builder0, simpleDialog_Builder1);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      SimpleDialog.Builder simpleDialog_Builder0 = new SimpleDialog.Builder();
      SimpleDialog.Builder simpleDialog_Builder1 = simpleDialog_Builder0.setMessage("5J~R6@");
      assertSame(simpleDialog_Builder0, simpleDialog_Builder1);
  }
}
