/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 10 02:50:08 GMT 2022
 */

package cn.byhieg.designpatterntutorial.builder;

import org.junit.Test;
import static org.junit.Assert.*;
import cn.byhieg.designpatterntutorial.builder.SimpleDialogController;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SimpleDialogController_ESTest extends SimpleDialogController_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SimpleDialogController simpleDialogController0 = new SimpleDialogController();
      simpleDialogController0.setTitle("ar$=+|6FSST}");
      String string0 = simpleDialogController0.getTitle();
      assertEquals("ar$=+|6FSST}", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SimpleDialogController simpleDialogController0 = new SimpleDialogController();
      simpleDialogController0.setTitle("");
      String string0 = simpleDialogController0.getTitle();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SimpleDialogController simpleDialogController0 = new SimpleDialogController();
      simpleDialogController0.setPositiveButton("G#0H$l4Q}%*x");
      String string0 = simpleDialogController0.getPositiveButton();
      assertEquals("G#0H$l4Q}%*x", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      SimpleDialogController simpleDialogController0 = new SimpleDialogController();
      simpleDialogController0.setNegativeButton("NIJ($1");
      String string0 = simpleDialogController0.getNegativeButton();
      assertEquals("NIJ($1", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SimpleDialogController simpleDialogController0 = new SimpleDialogController();
      simpleDialogController0.setMessage("!ju!dt{:Ym\"I`");
      String string0 = simpleDialogController0.getMessage();
      assertEquals("!ju!dt{:Ym\"I`", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      SimpleDialogController simpleDialogController0 = new SimpleDialogController();
      simpleDialogController0.setIcon("NIJ($1");
      String string0 = simpleDialogController0.getIcon();
      assertEquals("NIJ($1", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SimpleDialogController simpleDialogController0 = new SimpleDialogController();
      simpleDialogController0.setNegativeButton("");
      String string0 = simpleDialogController0.getNegativeButton();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SimpleDialogController.DialogParams simpleDialogController_DialogParams0 = new SimpleDialogController.DialogParams();
      simpleDialogController_DialogParams0.positiveButton = "Qu^GE";
      SimpleDialogController simpleDialogController0 = new SimpleDialogController();
      simpleDialogController_DialogParams0.apply(simpleDialogController0);
      assertNull(simpleDialogController0.getTitle());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SimpleDialogController simpleDialogController0 = new SimpleDialogController();
      SimpleDialogController.DialogParams simpleDialogController_DialogParams0 = new SimpleDialogController.DialogParams();
      simpleDialogController_DialogParams0.message = " 92";
      simpleDialogController_DialogParams0.apply(simpleDialogController0);
      assertNull(simpleDialogController0.getNegativeButton());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SimpleDialogController.DialogParams simpleDialogController_DialogParams0 = new SimpleDialogController.DialogParams();
      simpleDialogController_DialogParams0.title = "";
      SimpleDialogController simpleDialogController0 = new SimpleDialogController();
      simpleDialogController_DialogParams0.apply(simpleDialogController0);
      assertNull(simpleDialogController0.getIcon());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      SimpleDialogController simpleDialogController0 = new SimpleDialogController();
      String string0 = simpleDialogController0.getTitle();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      SimpleDialogController simpleDialogController0 = new SimpleDialogController();
      String string0 = simpleDialogController0.getMessage();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      SimpleDialogController simpleDialogController0 = new SimpleDialogController();
      simpleDialogController0.setMessage("");
      String string0 = simpleDialogController0.getMessage();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      SimpleDialogController simpleDialogController0 = new SimpleDialogController();
      String string0 = simpleDialogController0.getNegativeButton();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      SimpleDialogController simpleDialogController0 = new SimpleDialogController();
      String string0 = simpleDialogController0.getPositiveButton();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      SimpleDialogController simpleDialogController0 = new SimpleDialogController();
      SimpleDialogController.DialogParams simpleDialogController_DialogParams0 = new SimpleDialogController.DialogParams();
      simpleDialogController_DialogParams0.negativeButton = "";
      simpleDialogController_DialogParams0.apply(simpleDialogController0);
      assertNull(simpleDialogController0.getTitle());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      SimpleDialogController simpleDialogController0 = new SimpleDialogController();
      simpleDialogController0.setIcon("");
      String string0 = simpleDialogController0.getIcon();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      SimpleDialogController simpleDialogController0 = new SimpleDialogController();
      String string0 = simpleDialogController0.getIcon();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      SimpleDialogController simpleDialogController0 = new SimpleDialogController();
      simpleDialogController0.setPositiveButton("");
      String string0 = simpleDialogController0.getPositiveButton();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      SimpleDialogController.DialogParams simpleDialogController_DialogParams0 = new SimpleDialogController.DialogParams();
      SimpleDialogController simpleDialogController0 = new SimpleDialogController();
      simpleDialogController_DialogParams0.icon = "";
      simpleDialogController_DialogParams0.apply(simpleDialogController0);
      assertNull(simpleDialogController0.getPositiveButton());
  }
}
