/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 10 01:42:15 GMT 2022
 */

package cn.byhieg.collectiontutorial.maptutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import cn.byhieg.collectiontutorial.maptutorial.LinkedHashMapExample;
import java.util.LinkedHashMap;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LinkedHashMapExample_ESTest extends LinkedHashMapExample_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LinkedHashMapExample linkedHashMapExample0 = new LinkedHashMapExample();
      // Undeclared exception!
      try { 
        linkedHashMapExample0.printMaps((LinkedHashMap<? extends String, ? extends String>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("cn.byhieg.collectiontutorial.maptutorial.LinkedHashMapExample", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LinkedHashMapExample linkedHashMapExample0 = new LinkedHashMapExample();
      LinkedHashMap<String, String> linkedHashMap0 = linkedHashMapExample0.insertMap();
      linkedHashMapExample0.printMaps(linkedHashMap0);
      assertEquals(10, linkedHashMap0.size());
  }
}
