/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 10 01:31:24 GMT 2022
 */

package cn.byhieg.collectiontutorial.maptutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import cn.byhieg.collectiontutorial.maptutorial.TreeMapExample;
import java.util.TreeMap;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TreeMapExample_ESTest extends TreeMapExample_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      TreeMapExample treeMapExample0 = new TreeMapExample();
      TreeMap<String, String> treeMap0 = treeMapExample0.insertMap();
      treeMapExample0.getHigherEntry(treeMap0, "1");
      assertEquals(10, treeMap0.size());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TreeMapExample treeMapExample0 = new TreeMapExample();
      TreeMap<String, String> treeMap0 = new TreeMap<String, String>();
      // Undeclared exception!
      try { 
        treeMapExample0.getTailMap(treeMap0, (String) null, false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      TreeMapExample treeMapExample0 = new TreeMapExample();
      // Undeclared exception!
      try { 
        treeMapExample0.getSmallestEntry((TreeMap<String, String>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("cn.byhieg.collectiontutorial.maptutorial.TreeMapExample", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TreeMapExample treeMapExample0 = new TreeMapExample();
      TreeMap<String, String> treeMap0 = new TreeMap<String, String>();
      // Undeclared exception!
      try { 
        treeMapExample0.getRangeMap(treeMap0, (String) null, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TreeMapExample treeMapExample0 = new TreeMapExample();
      TreeMap<String, String> treeMap0 = new TreeMap<String, String>();
      // Undeclared exception!
      try { 
        treeMapExample0.getRangeMap(treeMap0, "XIHn{", "");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // fromKey > toKey
         //
         verifyException("java.util.TreeMap$NavigableSubMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      TreeMapExample treeMapExample0 = new TreeMapExample();
      TreeMap<String, String> treeMap0 = new TreeMap<String, String>();
      // Undeclared exception!
      try { 
        treeMapExample0.getLowestEntry(treeMap0, "P");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("cn.byhieg.collectiontutorial.maptutorial.TreeMapExample", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      TreeMapExample treeMapExample0 = new TreeMapExample();
      TreeMap<String, String> treeMap0 = new TreeMap<String, String>();
      // Undeclared exception!
      try { 
        treeMapExample0.getLargestEntry(treeMap0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("cn.byhieg.collectiontutorial.maptutorial.TreeMapExample", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      TreeMapExample treeMapExample0 = new TreeMapExample();
      TreeMap<String, String> treeMap0 = treeMapExample0.insertMap();
      // Undeclared exception!
      try { 
        treeMapExample0.getHeadMap(treeMap0, (String) null, false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      TreeMapExample treeMapExample0 = new TreeMapExample();
      TreeMap<String, String> treeMap0 = treeMapExample0.insertMap();
      treeMapExample0.getTailMap(treeMap0, "ivq3^!VW&dK@%wcB;G", true);
      assertEquals(10, treeMap0.size());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      TreeMapExample treeMapExample0 = new TreeMapExample();
      TreeMap<String, String> treeMap0 = treeMapExample0.insertMap();
      treeMapExample0.getHeadMap(treeMap0, "ivq3^!VW&dK@%wcB;G", true);
      assertEquals(10, treeMap0.size());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      TreeMapExample treeMapExample0 = new TreeMapExample();
      TreeMap<String, String> treeMap0 = treeMapExample0.insertMap();
      treeMapExample0.getRangeMap(treeMap0, "1", "ivq3^!VW&dK@%wcB;G");
      assertEquals(10, treeMap0.size());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      TreeMapExample treeMapExample0 = new TreeMapExample();
      TreeMap<String, String> treeMap0 = treeMapExample0.insertMap();
      treeMapExample0.getLargestEntry(treeMap0);
      assertEquals(10, treeMap0.size());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      TreeMapExample treeMapExample0 = new TreeMapExample();
      TreeMap<String, String> treeMap0 = treeMapExample0.insertMap();
      treeMapExample0.getSmallestEntry(treeMap0);
      assertEquals(10, treeMap0.size());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      TreeMapExample treeMapExample0 = new TreeMapExample();
      TreeMap<String, String> treeMap0 = treeMapExample0.insertMap();
      treeMapExample0.getLowestEntry(treeMap0, "ivq3^!VW&dK@%wcB;G");
      assertEquals(10, treeMap0.size());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      TreeMapExample treeMapExample0 = new TreeMapExample();
      TreeMap<String, String> treeMap0 = new TreeMap<String, String>();
      // Undeclared exception!
      try { 
        treeMapExample0.getHigherEntry(treeMap0, "cn.byhieg.collectiontutorial.maptutorial.TreeMapExample");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("cn.byhieg.collectiontutorial.maptutorial.TreeMapExample", e);
      }
  }
}
