/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 10 01:35:33 GMT 2022
 */

package cn.byhieg.annotationstutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import cn.byhieg.annotationstutorial.AConstructorProcess;
import cn.byhieg.annotationstutorial.User;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AConstructorProcess_ESTest extends AConstructorProcess_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      User user0 = new User();
      AConstructorProcess.init(user0);
      assertEquals(24, user0.age);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AConstructorProcess aConstructorProcess0 = new AConstructorProcess();
      // Undeclared exception!
      try { 
        AConstructorProcess.init(aConstructorProcess0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // \u65E0\u6CD5\u5411\u4E0B\u8F6C\u578B\u5230\u6307\u5B9A\u7C7B
         //
         verifyException("cn.byhieg.annotationstutorial.AConstructorProcess", e);
      }
  }
}
