/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 10 01:21:05 GMT 2022
 */

package cn.byhieg.iotutorial.bytestreamio;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import cn.byhieg.iotutorial.bytestreamio.BufferdInputStreamExample;
import java.io.FileNotFoundException;
import java.io.IOException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class BufferdInputStreamExample_ESTest extends BufferdInputStreamExample_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("D:/read_file.txt");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "8%CXaI<4AizI7={q$1");
      FileSystemHandling.shouldAllThrowIOExceptions();
      BufferdInputStreamExample bufferdInputStreamExample0 = new BufferdInputStreamExample();
      try { 
        bufferdInputStreamExample0.readFromFile();
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Simulated IOException
         //
         verifyException("org.evosuite.runtime.vfs.VirtualFileSystem", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("D:/read_file.txt");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "");
      BufferdInputStreamExample bufferdInputStreamExample0 = new BufferdInputStreamExample();
      bufferdInputStreamExample0.readFromFile();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      BufferdInputStreamExample bufferdInputStreamExample0 = new BufferdInputStreamExample();
      try { 
        bufferdInputStreamExample0.readFromFile();
        fail("Expecting exception: FileNotFoundException");
      
      } catch(FileNotFoundException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileInputStream", e);
      }
  }
}
