/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 10 02:24:49 GMT 2022
 */

package cn.byhieg.bitoperatetutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import cn.byhieg.bitoperatetutorial.BitOperate;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class BitOperate_ESTest extends BitOperate_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BitOperate bitOperate0 = new BitOperate();
      String string0 = bitOperate0.getRightestOne((-1));
      assertEquals("1", string0);
  }
}
