/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 10 02:47:57 GMT 2022
 */

package cn.byhieg.designpatterntutorial.proxy.dynamicproxy;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import cn.byhieg.designpatterntutorial.proxy.dynamicproxy.DynamicProxy;
import java.lang.reflect.Method;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DynamicProxy_ESTest extends DynamicProxy_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DynamicProxy dynamicProxy0 = new DynamicProxy((Object) null);
      Object[] objectArray0 = new Object[17];
      try { 
        dynamicProxy0.invoke((Object) null, (Method) null, objectArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("cn.byhieg.designpatterntutorial.proxy.dynamicproxy.DynamicProxy", e);
      }
  }
}
